# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from everos_cloud.models.topic_tag_write_data import TopicTagWriteData

class TestTopicTagWriteData(unittest.TestCase):
    """TopicTagWriteData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TopicTagWriteData:
        """Test TopicTagWriteData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TopicTagWriteData`
        """
        model = TopicTagWriteData()
        if include_optional:
            return TopicTagWriteData(
                topic_id = '',
                requested = 0.0,
                tag_ids = [
                    '0'
                    ],
                version = 0.0,
                truncated = True,
                limit = 50,
                dropped_count = 0.0
            )
        else:
            return TopicTagWriteData(
                topic_id = '',
                requested = 0.0,
                tag_ids = [
                    '0'
                    ],
                version = 0.0,
                truncated = True,
                limit = 50,
                dropped_count = 0.0,
        )
        """

    def testTopicTagWriteData(self):
        """Test TopicTagWriteData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
