# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from everos_cloud.models.success_envelope_search_data import SuccessEnvelopeSearchData

class TestSuccessEnvelopeSearchData(unittest.TestCase):
    """SuccessEnvelopeSearchData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccessEnvelopeSearchData:
        """Test SuccessEnvelopeSearchData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccessEnvelopeSearchData`
        """
        model = SuccessEnvelopeSearchData()
        if include_optional:
            return SuccessEnvelopeSearchData(
                request_id = '',
                data = everos_cloud.models.search_data.SearchData(
                    episodes = [
                        everos_cloud.models.search_episode_item.SearchEpisodeItem(
                            id = '', 
                            app_id = '', 
                            project_id = '', 
                            user_id = '', 
                            session_id = '', 
                            timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            sender_ids = [
                                ''
                                ], 
                            summary = '', 
                            subject = '', 
                            episode = '', 
                            readable_episode = '', 
                            type = '', 
                            atomic_facts = [
                                everos_cloud.models.search_atomic_fact_item.SearchAtomicFactItem(
                                    id = '', 
                                    content = '', 
                                    score = 1.337, )
                                ], 
                            tags = [
                                ''
                                ], 
                            score = 1.337, )
                        ], 
                    profiles = [
                        everos_cloud.models.search_profile_item.SearchProfileItem(
                            id = '', 
                            app_id = '', 
                            project_id = '', 
                            user_id = '', 
                            profile_data = { }, 
                            score = 1.337, )
                        ], 
                    agent_cases = [
                        everos_cloud.models.search_agent_case_item.SearchAgentCaseItem(
                            id = '', 
                            app_id = '', 
                            project_id = '', 
                            agent_id = '', 
                            session_id = '', 
                            task_intent = '', 
                            approach = '', 
                            quality_score = 1.337, 
                            key_insight = '', 
                            timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            score = 1.337, )
                        ], 
                    agent_skills = [
                        everos_cloud.models.search_agent_skill_item.SearchAgentSkillItem(
                            id = '', 
                            app_id = '', 
                            project_id = '', 
                            agent_id = '', 
                            name = '', 
                            description = '', 
                            content = '', 
                            confidence = 1.337, 
                            maturity_score = 1.337, 
                            source_case_ids = [
                                ''
                                ], 
                            score = 1.337, )
                        ], 
                    unprocessed_messages = [
                        everos_cloud.models.unprocessed_message_dto.UnprocessedMessageDTO(
                            id = '', 
                            app_id = '', 
                            project_id = '', 
                            session_id = '', 
                            sender_id = '', 
                            sender_name = '', 
                            role = 'user', 
                            content = null, 
                            timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            tool_calls = [
                                everos_cloud.models.tool_call.ToolCall(
                                    id = '', 
                                    type = 'function', 
                                    function = everos_cloud.models.tool_call_function.ToolCallFunction(
                                        name = '', 
                                        arguments = '', ), )
                                ], 
                            tool_call_id = '', )
                        ], )
            )
        else:
            return SuccessEnvelopeSearchData(
                request_id = '',
                data = everos_cloud.models.search_data.SearchData(
                    episodes = [
                        everos_cloud.models.search_episode_item.SearchEpisodeItem(
                            id = '', 
                            app_id = '', 
                            project_id = '', 
                            user_id = '', 
                            session_id = '', 
                            timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            sender_ids = [
                                ''
                                ], 
                            summary = '', 
                            subject = '', 
                            episode = '', 
                            readable_episode = '', 
                            type = '', 
                            atomic_facts = [
                                everos_cloud.models.search_atomic_fact_item.SearchAtomicFactItem(
                                    id = '', 
                                    content = '', 
                                    score = 1.337, )
                                ], 
                            tags = [
                                ''
                                ], 
                            score = 1.337, )
                        ], 
                    profiles = [
                        everos_cloud.models.search_profile_item.SearchProfileItem(
                            id = '', 
                            app_id = '', 
                            project_id = '', 
                            user_id = '', 
                            profile_data = { }, 
                            score = 1.337, )
                        ], 
                    agent_cases = [
                        everos_cloud.models.search_agent_case_item.SearchAgentCaseItem(
                            id = '', 
                            app_id = '', 
                            project_id = '', 
                            agent_id = '', 
                            session_id = '', 
                            task_intent = '', 
                            approach = '', 
                            quality_score = 1.337, 
                            key_insight = '', 
                            timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            score = 1.337, )
                        ], 
                    agent_skills = [
                        everos_cloud.models.search_agent_skill_item.SearchAgentSkillItem(
                            id = '', 
                            app_id = '', 
                            project_id = '', 
                            agent_id = '', 
                            name = '', 
                            description = '', 
                            content = '', 
                            confidence = 1.337, 
                            maturity_score = 1.337, 
                            source_case_ids = [
                                ''
                                ], 
                            score = 1.337, )
                        ], 
                    unprocessed_messages = [
                        everos_cloud.models.unprocessed_message_dto.UnprocessedMessageDTO(
                            id = '', 
                            app_id = '', 
                            project_id = '', 
                            session_id = '', 
                            sender_id = '', 
                            sender_name = '', 
                            role = 'user', 
                            content = null, 
                            timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            tool_calls = [
                                everos_cloud.models.tool_call.ToolCall(
                                    id = '', 
                                    type = 'function', 
                                    function = everos_cloud.models.tool_call_function.ToolCallFunction(
                                        name = '', 
                                        arguments = '', ), )
                                ], 
                            tool_call_id = '', )
                        ], ),
        )
        """

    def testSuccessEnvelopeSearchData(self):
        """Test SuccessEnvelopeSearchData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
