# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from everos_cloud.models.task_list_response import TaskListResponse

class TestTaskListResponse(unittest.TestCase):
    """TaskListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskListResponse:
        """Test TaskListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskListResponse`
        """
        model = TaskListResponse()
        if include_optional:
            return TaskListResponse(
                data = everos_cloud.models.task_list_response_data.TaskListResponse_data(
                    items = [
                        everos_cloud.models.task_item.TaskItem(
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            error = '', 
                            error_code = '', 
                            finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            id = '', 
                            object = '', 
                            object_id = '', 
                            status = 'queued', 
                            task_type = '', )
                        ], 
                    page = 56, 
                    page_size = 56, 
                    total = 56, ),
                request_id = ''
            )
        else:
            return TaskListResponse(
                data = everos_cloud.models.task_list_response_data.TaskListResponse_data(
                    items = [
                        everos_cloud.models.task_item.TaskItem(
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            error = '', 
                            error_code = '', 
                            finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            id = '', 
                            object = '', 
                            object_id = '', 
                            status = 'queued', 
                            task_type = '', )
                        ], 
                    page = 56, 
                    page_size = 56, 
                    total = 56, ),
        )
        """

    def testTaskListResponse(self):
        """Test TaskListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
