# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from everos_cloud.models.search_agent_skill_item import SearchAgentSkillItem

class TestSearchAgentSkillItem(unittest.TestCase):
    """SearchAgentSkillItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchAgentSkillItem:
        """Test SearchAgentSkillItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchAgentSkillItem`
        """
        model = SearchAgentSkillItem()
        if include_optional:
            return SearchAgentSkillItem(
                id = '',
                app_id = '',
                project_id = '',
                agent_id = '',
                name = '',
                description = '',
                content = '',
                confidence = 1.337,
                maturity_score = 1.337,
                source_case_ids = [
                    ''
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                score = 1.337
            )
        else:
            return SearchAgentSkillItem(
                id = '',
                app_id = '',
                project_id = '',
                agent_id = '',
                name = '',
                description = '',
                content = '',
                confidence = 1.337,
                maturity_score = 1.337,
                score = 1.337,
        )
        """

    def testSearchAgentSkillItem(self):
        """Test SearchAgentSkillItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
