# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from everos_cloud.models.success_envelope_edit_data import SuccessEnvelopeEditData

class TestSuccessEnvelopeEditData(unittest.TestCase):
    """SuccessEnvelopeEditData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccessEnvelopeEditData:
        """Test SuccessEnvelopeEditData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccessEnvelopeEditData`
        """
        model = SuccessEnvelopeEditData()
        if include_optional:
            return SuccessEnvelopeEditData(
                request_id = '',
                data = everos_cloud.models.edit_data.EditData(
                    user_id = '', 
                    version = 56, 
                    applied = 56, 
                    results = [
                        everos_cloud.models.edit_result_item.EditResultItem(
                            op_index = 56, 
                            action = '', 
                            type = '', 
                            status = 'applied', 
                            item_id = '', 
                            new_item_id = '', 
                            error = '', )
                        ], 
                    profile = { }, )
            )
        else:
            return SuccessEnvelopeEditData(
                request_id = '',
                data = everos_cloud.models.edit_data.EditData(
                    user_id = '', 
                    version = 56, 
                    applied = 56, 
                    results = [
                        everos_cloud.models.edit_result_item.EditResultItem(
                            op_index = 56, 
                            action = '', 
                            type = '', 
                            status = 'applied', 
                            item_id = '', 
                            new_item_id = '', 
                            error = '', )
                        ], 
                    profile = { }, ),
        )
        """

    def testSuccessEnvelopeEditData(self):
        """Test SuccessEnvelopeEditData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
