# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from everos_cloud_sdk.models.search_agent_case_item import SearchAgentCaseItem

class TestSearchAgentCaseItem(unittest.TestCase):
    """SearchAgentCaseItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchAgentCaseItem:
        """Test SearchAgentCaseItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchAgentCaseItem`
        """
        model = SearchAgentCaseItem()
        if include_optional:
            return SearchAgentCaseItem(
                id = '',
                app_id = '',
                project_id = '',
                agent_id = '',
                session_id = '',
                task_intent = '',
                approach = '',
                quality_score = 1.337,
                key_insight = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                score = 1.337
            )
        else:
            return SearchAgentCaseItem(
                id = '',
                app_id = '',
                project_id = '',
                agent_id = '',
                session_id = '',
                task_intent = '',
                approach = '',
                quality_score = 1.337,
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                score = 1.337,
        )
        """

    def testSearchAgentCaseItem(self):
        """Test SearchAgentCaseItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
