# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from everos_cloud_sdk.models.sign_response_item import SignResponseItem

class TestSignResponseItem(unittest.TestCase):
    """SignResponseItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignResponseItem:
        """Test SignResponseItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignResponseItem`
        """
        model = SignResponseItem()
        if include_optional:
            return SignResponseItem(
                file_id = '',
                file_name = '',
                file_type = '',
                object_key = '',
                object_url = '',
                object_signed_info = everos_cloud_sdk.models.signed_info.SignedInfo(
                    url = '', 
                    fields = {
                        'key' : ''
                        }, 
                    max_size = 56, )
            )
        else:
            return SignResponseItem(
        )
        """

    def testSignResponseItem(self):
        """Test SignResponseItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
