# coding: utf-8

"""
    EverOS Cloud Memory API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from everos_cloud_sdk.models.get_data import GetData

class TestGetData(unittest.TestCase):
    """GetData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetData:
        """Test GetData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetData`
        """
        model = GetData()
        if include_optional:
            return GetData(
                episodes = [
                    everos_cloud_sdk.models.episode_item.EpisodeItem(
                        id = '', 
                        app_id = '', 
                        project_id = '', 
                        user_id = '', 
                        session_id = '', 
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        sender_ids = [
                            ''
                            ], 
                        summary = '', 
                        subject = '', 
                        episode = '', 
                        type = '', 
                        atomic_facts = [
                            everos_cloud_sdk.models.atomic_fact_item.AtomicFactItem(
                                id = '', 
                                content = '', )
                            ], )
                    ],
                profiles = [
                    everos_cloud_sdk.models.profile_item.ProfileItem(
                        id = '', 
                        app_id = '', 
                        project_id = '', 
                        user_id = '', 
                        profile_data = { }, )
                    ],
                agent_cases = [
                    everos_cloud_sdk.models.agent_case_item.AgentCaseItem(
                        id = '', 
                        app_id = '', 
                        project_id = '', 
                        agent_id = '', 
                        session_id = '', 
                        task_intent = '', 
                        approach = '', 
                        quality_score = 1.337, 
                        key_insight = '', 
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                agent_skills = [
                    everos_cloud_sdk.models.agent_skill_item.AgentSkillItem(
                        id = '', 
                        app_id = '', 
                        project_id = '', 
                        agent_id = '', 
                        name = '', 
                        description = '', 
                        content = '', 
                        confidence = 1.337, 
                        maturity_score = 1.337, 
                        source_case_ids = [
                            ''
                            ], )
                    ],
                total_count = 56,
                count = 56
            )
        else:
            return GetData(
        )
        """

    def testGetData(self):
        """Test GetData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
