# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from everos_cloud.api.memory_api import MemoryApi


class TestMemoryApi(unittest.TestCase):
    """MemoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MemoryApi()

    def tearDown(self) -> None:
        pass

    def test_add_memory(self) -> None:
        """Test case for add_memory

        Add messages [OSS + Cloud]
        """
        pass

    def test_bind_tags(self) -> None:
        """Test case for bind_tags

        Bind tags to memories [Cloud]
        """
        pass

    def test_delete_memories_by_ids(self) -> None:
        """Test case for delete_memories_by_ids

        Soft-delete memory records by id [Cloud-only]
        """
        pass

    def test_delete_memory(self) -> None:
        """Test case for delete_memory

        Delete memories [Cloud-only]
        """
        pass

    def test_edit_profile(self) -> None:
        """Test case for edit_profile

        Edit profile items [Cloud-only]
        """
        pass

    def test_flush_memory(self) -> None:
        """Test case for flush_memory

        Force memory extraction [OSS + Cloud]
        """
        pass

    def test_get_memory(self) -> None:
        """Test case for get_memory

        Get memories [OSS + Cloud]
        """
        pass

    def test_replace_tags(self) -> None:
        """Test case for replace_tags

        Replace tags on memories [Cloud]
        """
        pass

    def test_search_memory(self) -> None:
        """Test case for search_memory

        Search memories [OSS + Cloud]
        """
        pass

    def test_submit_feedback(self) -> None:
        """Test case for submit_feedback

        Submit feedback about one memory [Cloud-only]
        """
        pass

    def test_unbind_tags(self) -> None:
        """Test case for unbind_tags

        Unbind tags from memories [Cloud]
        """
        pass

    def test_update_memory(self) -> None:
        """Test case for update_memory

        Edit one memory record [Cloud-only]
        """
        pass


if __name__ == '__main__':
    unittest.main()
