# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from everos_cloud.api.knowledge_api import KnowledgeApi


class TestKnowledgeApi(unittest.TestCase):
    """KnowledgeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = KnowledgeApi()

    def tearDown(self) -> None:
        pass

    def test_create_category(self) -> None:
        """Test case for create_category

        Create a category
        """
        pass

    def test_create_document(self) -> None:
        """Test case for create_document

        Upload a document
        """
        pass

    def test_create_knowledge_base(self) -> None:
        """Test case for create_knowledge_base

        Create a knowledge base
        """
        pass

    def test_delete_category(self) -> None:
        """Test case for delete_category

        Delete a category
        """
        pass

    def test_delete_document(self) -> None:
        """Test case for delete_document

        Delete a document
        """
        pass

    def test_delete_knowledge_base(self) -> None:
        """Test case for delete_knowledge_base

        Delete a knowledge base
        """
        pass

    def test_get_document(self) -> None:
        """Test case for get_document

        Get a document
        """
        pass

    def test_get_knowledge_base(self) -> None:
        """Test case for get_knowledge_base

        Get a knowledge base
        """
        pass

    def test_get_topic(self) -> None:
        """Test case for get_topic

        Get a topic
        """
        pass

    def test_list_categories(self) -> None:
        """Test case for list_categories

        List categories
        """
        pass

    def test_list_documents(self) -> None:
        """Test case for list_documents

        List documents
        """
        pass

    def test_list_knowledge_bases(self) -> None:
        """Test case for list_knowledge_bases

        List knowledge bases
        """
        pass

    def test_list_topics(self) -> None:
        """Test case for list_topics

        List a document's topics
        """
        pass

    def test_list_topics_by_tags(self) -> None:
        """Test case for list_topics_by_tags

        List topics by tag
        """
        pass

    def test_query_related_tags(self) -> None:
        """Test case for query_related_tags

        Count tag usage
        """
        pass

    def test_replace_document(self) -> None:
        """Test case for replace_document

        Replace a document
        """
        pass

    def test_replace_topic_tags(self) -> None:
        """Test case for replace_topic_tags

        Replace a topic's tags
        """
        pass

    def test_search_knowledge(self) -> None:
        """Test case for search_knowledge

        Search a knowledge base
        """
        pass

    def test_update_category(self) -> None:
        """Test case for update_category

        Update a category
        """
        pass

    def test_update_document(self) -> None:
        """Test case for update_document

        Update a document
        """
        pass

    def test_update_knowledge_base(self) -> None:
        """Test case for update_knowledge_base

        Update a knowledge base
        """
        pass


if __name__ == '__main__':
    unittest.main()
