# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from everos_cloud.models.add_input import AddInput

class TestAddInput(unittest.TestCase):
    """AddInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddInput:
        """Test AddInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddInput`
        """
        model = AddInput()
        if include_optional:
            return AddInput(
                app_id = 'default',
                project_id = 'default',
                session_id = '0',
                mode = 'chat',
                messages = [
                    everos_cloud.models.message_item.MessageItem(
                        sender_id = '', 
                        sender_name = '', 
                        role = 'user', 
                        timestamp = 56, 
                        content = null, 
                        tool_calls = [
                            everos_cloud.models.tool_call.ToolCall(
                                id = '', 
                                type = 'function', 
                                function = everos_cloud.models.tool_call_function.ToolCallFunction(
                                    name = '', 
                                    arguments = '', ), )
                            ], 
                        tool_call_id = '', )
                    ],
                async_mode = True
            )
        else:
            return AddInput(
                session_id = '0',
                messages = [
                    everos_cloud.models.message_item.MessageItem(
                        sender_id = '', 
                        sender_name = '', 
                        role = 'user', 
                        timestamp = 56, 
                        content = null, 
                        tool_calls = [
                            everos_cloud.models.tool_call.ToolCall(
                                id = '', 
                                type = 'function', 
                                function = everos_cloud.models.tool_call_function.ToolCallFunction(
                                    name = '', 
                                    arguments = '', ), )
                            ], 
                        tool_call_id = '', )
                    ],
        )
        """

    def testAddInput(self):
        """Test AddInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
