# coding: utf-8

"""
    EverOS Cloud Memory API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from everos_cloud_sdk.models.edit_data import EditData

class TestEditData(unittest.TestCase):
    """EditData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EditData:
        """Test EditData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EditData`
        """
        model = EditData()
        if include_optional:
            return EditData(
                user_id = '',
                version = 56,
                applied = 56,
                results = [
                    everos_cloud_sdk.models.edit_result_item.EditResultItem(
                        op_index = 56, 
                        action = '', 
                        type = '', 
                        status = 'applied', 
                        item_id = '', 
                        new_item_id = '', 
                        error = '', )
                    ],
                profile = { }
            )
        else:
            return EditData(
                user_id = '',
                version = 56,
                applied = 56,
        )
        """

    def testEditData(self):
        """Test EditData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
