# coding: utf-8

"""
    EverOS Cloud Memory API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from everos_cloud_sdk.models.search_profile_item import SearchProfileItem

class TestSearchProfileItem(unittest.TestCase):
    """SearchProfileItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchProfileItem:
        """Test SearchProfileItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchProfileItem`
        """
        model = SearchProfileItem()
        if include_optional:
            return SearchProfileItem(
                id = '',
                app_id = '',
                project_id = '',
                user_id = '',
                profile_data = { },
                score = 1.337
            )
        else:
            return SearchProfileItem(
                id = '',
                app_id = '',
                project_id = '',
                user_id = '',
        )
        """

    def testSearchProfileItem(self):
        """Test SearchProfileItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
