# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from everos_cloud.models.search_input import SearchInput

class TestSearchInput(unittest.TestCase):
    """SearchInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchInput:
        """Test SearchInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchInput`
        """
        model = SearchInput()
        if include_optional:
            return SearchInput(
                app_id = 'default',
                project_id = 'default',
                user_id = '0',
                agent_id = '0',
                query = '0',
                method = 'hybrid',
                top_k = 56,
                radius = 0.0,
                min_score = 0.0,
                include_profile = True,
                with_readable_episode = True,
                enable_llm_rerank = True,
                filters = { }
            )
        else:
            return SearchInput(
                query = '0',
        )
        """

    def testSearchInput(self):
        """Test SearchInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
