# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from everos_cloud.models.unprocessed_message_dto import UnprocessedMessageDTO

class TestUnprocessedMessageDTO(unittest.TestCase):
    """UnprocessedMessageDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnprocessedMessageDTO:
        """Test UnprocessedMessageDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnprocessedMessageDTO`
        """
        model = UnprocessedMessageDTO()
        if include_optional:
            return UnprocessedMessageDTO(
                id = '',
                app_id = '',
                project_id = '',
                session_id = '',
                sender_id = '',
                sender_name = '',
                role = 'user',
                content = None,
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                tool_calls = [
                    everos_cloud.models.tool_call.ToolCall(
                        id = '', 
                        type = 'function', 
                        function = everos_cloud.models.tool_call_function.ToolCallFunction(
                            name = '', 
                            arguments = '', ), )
                    ],
                tool_call_id = ''
            )
        else:
            return UnprocessedMessageDTO(
                id = '',
                app_id = '',
                project_id = '',
                session_id = '',
                sender_id = '',
                role = 'user',
                content = None,
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testUnprocessedMessageDTO(self):
        """Test UnprocessedMessageDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
