# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from everos_cloud.models.success_envelope_topic_detail_data import SuccessEnvelopeTopicDetailData

class TestSuccessEnvelopeTopicDetailData(unittest.TestCase):
    """SuccessEnvelopeTopicDetailData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccessEnvelopeTopicDetailData:
        """Test SuccessEnvelopeTopicDetailData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccessEnvelopeTopicDetailData`
        """
        model = SuccessEnvelopeTopicDetailData()
        if include_optional:
            return SuccessEnvelopeTopicDetailData(
                request_id = '',
                data = everos_cloud.models.topic_detail_data.TopicDetailData(
                    id = '', 
                    doc_id = '', 
                    kb_id = '', 
                    category_id = '', 
                    category_name = '', 
                    name = '', 
                    depth = 56, 
                    seq = 56, 
                    summary = '', 
                    content = '', 
                    labels = [
                        ''
                        ], 
                    parent_id = '', 
                    children_ids = [
                        ''
                        ], 
                    metadata = { }, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return SuccessEnvelopeTopicDetailData(
                request_id = '',
                data = everos_cloud.models.topic_detail_data.TopicDetailData(
                    id = '', 
                    doc_id = '', 
                    kb_id = '', 
                    category_id = '', 
                    category_name = '', 
                    name = '', 
                    depth = 56, 
                    seq = 56, 
                    summary = '', 
                    content = '', 
                    labels = [
                        ''
                        ], 
                    parent_id = '', 
                    children_ids = [
                        ''
                        ], 
                    metadata = { }, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
        )
        """

    def testSuccessEnvelopeTopicDetailData(self):
        """Test SuccessEnvelopeTopicDetailData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
