# coding: utf-8

"""
    EverOS Cloud Memory API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from everos_cloud_sdk.models.agent_case_item import AgentCaseItem

class TestAgentCaseItem(unittest.TestCase):
    """AgentCaseItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentCaseItem:
        """Test AgentCaseItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentCaseItem`
        """
        model = AgentCaseItem()
        if include_optional:
            return AgentCaseItem(
                id = '',
                app_id = '',
                project_id = '',
                agent_id = '',
                session_id = '',
                task_intent = '',
                approach = '',
                quality_score = 1.337,
                key_insight = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return AgentCaseItem(
                id = '',
                app_id = '',
                project_id = '',
                agent_id = '',
                session_id = '',
                task_intent = '',
                approach = '',
                quality_score = 1.337,
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testAgentCaseItem(self):
        """Test AgentCaseItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
