# coding: utf-8

"""
    EverOS Cloud Memory API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from everos_cloud_sdk.models.episode_item import EpisodeItem

class TestEpisodeItem(unittest.TestCase):
    """EpisodeItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EpisodeItem:
        """Test EpisodeItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EpisodeItem`
        """
        model = EpisodeItem()
        if include_optional:
            return EpisodeItem(
                id = '',
                app_id = '',
                project_id = '',
                user_id = '',
                session_id = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                sender_ids = [
                    ''
                    ],
                summary = '',
                subject = '',
                episode = '',
                type = '',
                atomic_facts = [
                    everos_cloud_sdk.models.atomic_fact_item.AtomicFactItem(
                        id = '', 
                        content = '', )
                    ]
            )
        else:
            return EpisodeItem(
                id = '',
                app_id = '',
                project_id = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                summary = '',
                subject = '',
                episode = '',
                type = '',
        )
        """

    def testEpisodeItem(self):
        """Test EpisodeItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
