# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from everos_cloud.models.success_envelope_topic_tag_write_data import SuccessEnvelopeTopicTagWriteData

class TestSuccessEnvelopeTopicTagWriteData(unittest.TestCase):
    """SuccessEnvelopeTopicTagWriteData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccessEnvelopeTopicTagWriteData:
        """Test SuccessEnvelopeTopicTagWriteData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccessEnvelopeTopicTagWriteData`
        """
        model = SuccessEnvelopeTopicTagWriteData()
        if include_optional:
            return SuccessEnvelopeTopicTagWriteData(
                request_id = '',
                data = { }
            )
        else:
            return SuccessEnvelopeTopicTagWriteData(
                request_id = '',
                data = { },
        )
        """

    def testSuccessEnvelopeTopicTagWriteData(self):
        """Test SuccessEnvelopeTopicTagWriteData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
