# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from everos_cloud.models.kb_search_data import KbSearchData

class TestKbSearchData(unittest.TestCase):
    """KbSearchData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KbSearchData:
        """Test KbSearchData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KbSearchData`
        """
        model = KbSearchData()
        if include_optional:
            return KbSearchData(
                hits = [
                    everos_cloud.models.search_hit.SearchHit(
                        object = 'topic', 
                        id = '', 
                        doc_id = '', 
                        kb_id = '', 
                        category_id = '', 
                        category_name = '', 
                        name = '', 
                        depth = 56, 
                        summary = '', 
                        content = '', 
                        score = 1.337, 
                        retrieval_method = 'hybrid', 
                        source = '', 
                        document = everos_cloud.models.document_context.DocumentContext(
                            doc_id = '', 
                            title = '', 
                            summary = '', ), )
                    ],
                total = 56,
                took_ms = 1.337
            )
        else:
            return KbSearchData(
        )
        """

    def testKbSearchData(self):
        """Test KbSearchData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
