# coding: utf-8

"""
    EverOS Cloud Memory API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from everos_cloud_sdk.models.message_item import MessageItem

class TestMessageItem(unittest.TestCase):
    """MessageItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessageItem:
        """Test MessageItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessageItem`
        """
        model = MessageItem()
        if include_optional:
            return MessageItem(
                sender_id = '',
                sender_name = '',
                role = 'user',
                timestamp = 56,
                content = None,
                tool_calls = [
                    everos_cloud_sdk.models.tool_call.ToolCall(
                        id = '', 
                        type = 'function', 
                        function = everos_cloud_sdk.models.tool_call_function.ToolCallFunction(
                            name = '', 
                            arguments = '', ), )
                    ],
                tool_call_id = ''
            )
        else:
            return MessageItem(
                sender_id = '',
                role = 'user',
                timestamp = 56,
                content = None,
        )
        """

    def testMessageItem(self):
        """Test MessageItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
