# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from everos_cloud.models.tag_bind_input import TagBindInput

class TestTagBindInput(unittest.TestCase):
    """TagBindInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TagBindInput:
        """Test TagBindInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TagBindInput`
        """
        model = TagBindInput()
        if include_optional:
            return TagBindInput(
                memory_type = '0',
                memory_ids = [
                    ''
                    ],
                tags = [
                    '0'
                    ]
            )
        else:
            return TagBindInput(
                memory_type = '0',
                memory_ids = [
                    ''
                    ],
                tags = [
                    '0'
                    ],
        )
        """

    def testTagBindInput(self):
        """Test TagBindInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
