# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from everos_cloud.models.tag_ref import TagRef
from typing import Optional, Set
from typing_extensions import Self

class DocData(BaseModel):
    """
    A document as returned to clients. ``topic_count`` = the node_count (>0 = ingested).  Contract note — ``topic_count`` vs ``GET .../topics``: the count is of REAL topics and excludes the synthetic document-root node, while the topics list INCLUDES it. So ``len(topics) == topic_count + 1`` for an ingested document. See ``TopicListData``.
    """ # noqa: E501
    id: StrictStr = Field(description="Document id (bare primary key)")
    kb_id: StrictStr = Field(description="The knowledge base this document belongs to.")
    category_id: Optional[StrictStr] = Field(default='', description="The category it is filed under; empty when it is uncategorized.")
    category_name: Optional[StrictStr] = None
    title: StrictStr = Field(description="The document's title.")
    summary: Optional[StrictStr] = None
    source_name: Optional[StrictStr] = None
    source_type: Optional[StrictStr] = None
    tags: List[TagRef] = Field(description="Distinct opaque ids from the document's read-only topic-tag union. Cloud leaves name unset; KHS may validate and expand display names. This document aggregate is read-only and carries no topic ownership field.")
    topic_count: Optional[StrictInt] = Field(default=0, description="Number of real topics extracted (0 = not ingested yet / ingest failed). EXCLUDES the synthetic document-root node, so `GET .../topics` — which includes it — returns exactly one more item than this")
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "kb_id", "category_id", "category_name", "title", "summary", "source_name", "source_type", "tags", "topic_count", "created_at", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DocData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item_tags in self.tags:
                if _item_tags:
                    _items.append(_item_tags.to_dict())
            _dict['tags'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if category_name (nullable) is None
        # and model_fields_set contains the field
        if self.category_name is None and "category_name" in self.model_fields_set:
            _dict['category_name'] = None

        # set to None if summary (nullable) is None
        # and model_fields_set contains the field
        if self.summary is None and "summary" in self.model_fields_set:
            _dict['summary'] = None

        # set to None if source_name (nullable) is None
        # and model_fields_set contains the field
        if self.source_name is None and "source_name" in self.model_fields_set:
            _dict['source_name'] = None

        # set to None if source_type (nullable) is None
        # and model_fields_set contains the field
        if self.source_type is None and "source_type" in self.model_fields_set:
            _dict['source_type'] = None

        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['created_at'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updated_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DocData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "kb_id": obj.get("kb_id"),
            "category_id": obj.get("category_id") if obj.get("category_id") is not None else '',
            "category_name": obj.get("category_name"),
            "title": obj.get("title"),
            "summary": obj.get("summary"),
            "source_name": obj.get("source_name"),
            "source_type": obj.get("source_type"),
            "tags": [TagRef.from_dict(_item) for _item in obj["tags"]] if obj.get("tags") is not None else None,
            "topic_count": obj.get("topic_count") if obj.get("topic_count") is not None else 0,
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


