# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from everos_cloud.models.add_operation import AddOperation
from everos_cloud.models.delete_operation import DeleteOperation
from everos_cloud.models.update_operation import UpdateOperation
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

EDITINPUTOPERATIONSINNER_ONE_OF_SCHEMAS = ["AddOperation", "DeleteOperation", "UpdateOperation"]

class EditInputOperationsInner(BaseModel):
    """
    EditInputOperationsInner
    """
    # data type: AddOperation
    oneof_schema_1_validator: Optional[AddOperation] = None
    # data type: UpdateOperation
    oneof_schema_2_validator: Optional[UpdateOperation] = None
    # data type: DeleteOperation
    oneof_schema_3_validator: Optional[DeleteOperation] = None
    actual_instance: Optional[Union[AddOperation, DeleteOperation, UpdateOperation]] = None
    one_of_schemas: Set[str] = { "AddOperation", "DeleteOperation", "UpdateOperation" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = EditInputOperationsInner.model_construct()
        error_messages = []
        match = 0
        # validate data type: AddOperation
        if not isinstance(v, AddOperation):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AddOperation`")
        else:
            match += 1
        # validate data type: UpdateOperation
        if not isinstance(v, UpdateOperation):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UpdateOperation`")
        else:
            match += 1
        # validate data type: DeleteOperation
        if not isinstance(v, DeleteOperation):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DeleteOperation`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in EditInputOperationsInner with oneOf schemas: AddOperation, DeleteOperation, UpdateOperation. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in EditInputOperationsInner with oneOf schemas: AddOperation, DeleteOperation, UpdateOperation. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # use oneOf discriminator to lookup the data type
        _data_type = json.loads(json_str).get("action")
        if not _data_type:
            raise ValueError("Failed to lookup data type from the field `action` in the input.")

        # check if data type is `AddOperation`
        if _data_type == "add":
            instance.actual_instance = AddOperation.from_json(json_str)
            return instance

        # check if data type is `DeleteOperation`
        if _data_type == "delete":
            instance.actual_instance = DeleteOperation.from_json(json_str)
            return instance

        # check if data type is `UpdateOperation`
        if _data_type == "update":
            instance.actual_instance = UpdateOperation.from_json(json_str)
            return instance

        # check if data type is `AddOperation`
        if _data_type == "AddOperation":
            instance.actual_instance = AddOperation.from_json(json_str)
            return instance

        # check if data type is `DeleteOperation`
        if _data_type == "DeleteOperation":
            instance.actual_instance = DeleteOperation.from_json(json_str)
            return instance

        # check if data type is `UpdateOperation`
        if _data_type == "UpdateOperation":
            instance.actual_instance = UpdateOperation.from_json(json_str)
            return instance

        # deserialize data into AddOperation
        try:
            instance.actual_instance = AddOperation.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UpdateOperation
        try:
            instance.actual_instance = UpdateOperation.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DeleteOperation
        try:
            instance.actual_instance = DeleteOperation.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into EditInputOperationsInner with oneOf schemas: AddOperation, DeleteOperation, UpdateOperation. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into EditInputOperationsInner with oneOf schemas: AddOperation, DeleteOperation, UpdateOperation. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], AddOperation, DeleteOperation, UpdateOperation]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


