# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class FeedbackInput(BaseModel):
    """
    Rate one memory record [Cloud-only].  The target is addressed the way the read APIs return it: ``memory_type`` + ``memory_id``, plus ``item_id`` for a profile, whose rateable unit is one item inside ``profile_data`` rather than the whole document. Everything identifying (tenant, submitter) is derived on the server; the whitelist is closed.  A reason is DESCRIPTIVE. No code triggers a mutation by itself — ``privacy`` in particular is a signal, not a deletion request.
    """ # noqa: E501
    memory_type: StrictStr = Field(description="Kind of the target memory, as named by memory.get / search.")
    memory_id: Annotated[str, Field(min_length=24, strict=True, max_length=24)] = Field(description="The target's `id` from memory.get / search (the profile document's id for `profile`).")
    item_id: Optional[Annotated[str, Field(strict=True)]] = None
    rating: StrictStr = Field(description="Direction of the explicit assessment.")
    reason: Optional[StrictStr] = None
    note: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=256)]] = None
    suggestion: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=8000)]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["memory_type", "memory_id", "item_id", "rating", "reason", "note", "suggestion"]

    @field_validator('memory_type')
    def memory_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['episode', 'profile', 'agent_case', 'agent_skill']):
            raise ValueError("must be one of enum values ('episode', 'profile', 'agent_case', 'agent_skill')")
        return value

    @field_validator('memory_id')
    def memory_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[0-9a-fA-F]{24}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9a-fA-F]{24}$/")
        return value

    @field_validator('item_id')
    def item_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(ei|it)_[0-9a-f]{24}$", value):
            raise ValueError(r"must validate the regular expression /^(ei|it)_[0-9a-f]{24}$/")
        return value

    @field_validator('rating')
    def rating_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['positive', 'negative']):
            raise ValueError("must be one of enum values ('positive', 'negative')")
        return value

    @field_validator('reason')
    def reason_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['hallucination', 'outdated', 'wrong_subject', 'wrong_time', 'redundant', 'privacy', 'style', 'other']):
            raise ValueError("must be one of enum values ('hallucination', 'outdated', 'wrong_subject', 'wrong_time', 'redundant', 'privacy', 'style', 'other')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FeedbackInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if item_id (nullable) is None
        # and model_fields_set contains the field
        if self.item_id is None and "item_id" in self.model_fields_set:
            _dict['item_id'] = None

        # set to None if reason (nullable) is None
        # and model_fields_set contains the field
        if self.reason is None and "reason" in self.model_fields_set:
            _dict['reason'] = None

        # set to None if note (nullable) is None
        # and model_fields_set contains the field
        if self.note is None and "note" in self.model_fields_set:
            _dict['note'] = None

        # set to None if suggestion (nullable) is None
        # and model_fields_set contains the field
        if self.suggestion is None and "suggestion" in self.model_fields_set:
            _dict['suggestion'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FeedbackInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "memory_type": obj.get("memory_type"),
            "memory_id": obj.get("memory_id"),
            "item_id": obj.get("item_id"),
            "rating": obj.get("rating"),
            "reason": obj.get("reason"),
            "note": obj.get("note"),
            "suggestion": obj.get("suggestion")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


