# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from everos_cloud.models.search_atomic_fact_item import SearchAtomicFactItem
from typing import Optional, Set
from typing_extensions import Self

class SearchEpisodeItem(BaseModel):
    """
    SearchEpisodeItem
    """ # noqa: E501
    id: StrictStr = Field(description="Episode id. Use it to bind tags or to fetch this episode again.")
    app_id: StrictStr = Field(description="The business-semantic scope this memory was written under.")
    project_id: StrictStr = Field(description="Second half of that scope.")
    user_id: Optional[StrictStr] = None
    session_id: Optional[StrictStr] = None
    timestamp: datetime = Field(description="When the remembered exchange happened (ISO 8601), not when it was extracted.")
    sender_ids: Optional[List[StrictStr]] = Field(default=None, description="The senders that appear in the source exchange.")
    summary: StrictStr = Field(description="Short summary of the episode — what a result list should show.")
    subject: StrictStr = Field(description="What the episode is about, in a few words.")
    episode: StrictStr = Field(description="The episode's stored narrative body. This is the indexed, searchable text.")
    readable_episode: Optional[StrictStr] = None
    type: StrictStr = Field(description="How the episode was produced — \"Conversation\" or \"AgentConversation\".")
    atomic_facts: Optional[List[SearchAtomicFactItem]] = Field(default=None, description="The facts extracted from this episode, each with its own relevance score.")
    tags: Optional[List[StrictStr]] = Field(default=None, description="Tags attached through /api/v2/memory/tag/*.")
    score: Union[StrictFloat, StrictInt] = Field(description="Relevance of this episode to the query. What the number means depends on `method`: the hybrid path fuses its two routes into a probability in 0.0–1.0 (which is what `min_score` filters on), while keyword and vector pass the underlying engine's own score through — BM25 has no upper bound and vector similarity depends on the metric. So compare scores within one method, not across methods.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "app_id", "project_id", "user_id", "session_id", "timestamp", "sender_ids", "summary", "subject", "episode", "readable_episode", "type", "atomic_facts", "tags", "score"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchEpisodeItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in atomic_facts (list)
        _items = []
        if self.atomic_facts:
            for _item_atomic_facts in self.atomic_facts:
                if _item_atomic_facts:
                    _items.append(_item_atomic_facts.to_dict())
            _dict['atomic_facts'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if user_id (nullable) is None
        # and model_fields_set contains the field
        if self.user_id is None and "user_id" in self.model_fields_set:
            _dict['user_id'] = None

        # set to None if session_id (nullable) is None
        # and model_fields_set contains the field
        if self.session_id is None and "session_id" in self.model_fields_set:
            _dict['session_id'] = None

        # set to None if readable_episode (nullable) is None
        # and model_fields_set contains the field
        if self.readable_episode is None and "readable_episode" in self.model_fields_set:
            _dict['readable_episode'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchEpisodeItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "app_id": obj.get("app_id"),
            "project_id": obj.get("project_id"),
            "user_id": obj.get("user_id"),
            "session_id": obj.get("session_id"),
            "timestamp": obj.get("timestamp"),
            "sender_ids": obj.get("sender_ids"),
            "summary": obj.get("summary"),
            "subject": obj.get("subject"),
            "episode": obj.get("episode"),
            "readable_episode": obj.get("readable_episode"),
            "type": obj.get("type"),
            "atomic_facts": [SearchAtomicFactItem.from_dict(_item) for _item in obj["atomic_facts"]] if obj.get("atomic_facts") is not None else None,
            "tags": obj.get("tags"),
            "score": obj.get("score")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


