# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from everos_cloud.models.document_context import DocumentContext
from typing import Optional, Set
from typing_extensions import Self

class SearchHit(BaseModel):
    """
    A single search hit. ``object`` self-describes the unit (currently always topic).
    """ # noqa: E501
    object: Optional[StrictStr] = 'topic'
    id: StrictStr
    doc_id: StrictStr
    kb_id: StrictStr
    category_id: Optional[StrictStr] = ''
    category_name: Optional[StrictStr] = None
    name: Optional[StrictStr] = ''
    depth: Optional[StrictInt] = 0
    summary: Optional[StrictStr] = ''
    content: Optional[StrictStr] = None
    score: Optional[Union[StrictFloat, StrictInt]] = 0.0
    retrieval_method: Optional[StrictStr] = 'hybrid'
    source: Optional[StrictStr] = None
    document: Optional[DocumentContext] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["object", "id", "doc_id", "kb_id", "category_id", "category_name", "name", "depth", "summary", "content", "score", "retrieval_method", "source", "document"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchHit from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of document
        if self.document:
            _dict['document'] = self.document.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if category_name (nullable) is None
        # and model_fields_set contains the field
        if self.category_name is None and "category_name" in self.model_fields_set:
            _dict['category_name'] = None

        # set to None if content (nullable) is None
        # and model_fields_set contains the field
        if self.content is None and "content" in self.model_fields_set:
            _dict['content'] = None

        # set to None if source (nullable) is None
        # and model_fields_set contains the field
        if self.source is None and "source" in self.model_fields_set:
            _dict['source'] = None

        # set to None if document (nullable) is None
        # and model_fields_set contains the field
        if self.document is None and "document" in self.model_fields_set:
            _dict['document'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchHit from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "object": obj.get("object") if obj.get("object") is not None else 'topic',
            "id": obj.get("id"),
            "doc_id": obj.get("doc_id"),
            "kb_id": obj.get("kb_id"),
            "category_id": obj.get("category_id") if obj.get("category_id") is not None else '',
            "category_name": obj.get("category_name"),
            "name": obj.get("name") if obj.get("name") is not None else '',
            "depth": obj.get("depth") if obj.get("depth") is not None else 0,
            "summary": obj.get("summary") if obj.get("summary") is not None else '',
            "content": obj.get("content"),
            "score": obj.get("score") if obj.get("score") is not None else 0.0,
            "retrieval_method": obj.get("retrieval_method") if obj.get("retrieval_method") is not None else 'hybrid',
            "source": obj.get("source"),
            "document": DocumentContext.from_dict(obj["document"]) if obj.get("document") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


