# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class SearchAgentSkillItem(BaseModel):
    """
    SearchAgentSkillItem
    """ # noqa: E501
    id: StrictStr = Field(description="Agent-skill id.")
    app_id: StrictStr = Field(description="The business-semantic scope this skill was written under.")
    project_id: StrictStr = Field(description="Second half of that scope.")
    agent_id: StrictStr = Field(description="The agent that owns this skill.")
    name: StrictStr = Field(description="The skill's name.")
    description: StrictStr = Field(description="What the skill is for, in a sentence.")
    content: StrictStr = Field(description="The skill itself — the reusable procedure, ready to put in a prompt.")
    confidence: Union[StrictFloat, StrictInt] = Field(description="How much the distillation trusts this skill. Nominally 0.0–1.0, defaulting to 0.0 before anything scores it; the range is not enforced on the write path. Nothing in retrieval filters on it today, and how it divides labour with `maturity_score` is still open — so do not build a threshold on it yet.")
    maturity_score: Union[StrictFloat, StrictInt] = Field(description="How well-established the skill is. Nominally 0.0–1.0 and unenforced, and — unlike the other two scores — its default is 0.6 rather than 0.0, chosen so an unscored skill starts mid-optimistic. The cost is that an unscored 0.6 is indistinguishable from a scored 0.6: there is no \"not evaluated\" sentinel, and maturity scoring is skipped by default. Filtering near 0.6 is therefore unreliable.")
    source_case_ids: Optional[List[StrictStr]] = Field(default=None, description="The agent cases this skill was distilled from. Fetch them for the underlying evidence.")
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    score: Union[StrictFloat, StrictInt] = Field(description="Relevance of this skill to the query.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "app_id", "project_id", "agent_id", "name", "description", "content", "confidence", "maturity_score", "source_case_ids", "created_at", "updated_at", "score"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchAgentSkillItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['created_at'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updated_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchAgentSkillItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "app_id": obj.get("app_id"),
            "project_id": obj.get("project_id"),
            "agent_id": obj.get("agent_id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "content": obj.get("content"),
            "confidence": obj.get("confidence"),
            "maturity_score": obj.get("maturity_score"),
            "source_case_ids": obj.get("source_case_ids"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "score": obj.get("score")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


