# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from everos_cloud.models.search_filters import SearchFilters
from typing import Optional, Set
from typing_extensions import Self

class SearchBody(BaseModel):
    """
    POST body (kb_id rides the path, not the body).
    """ # noqa: E501
    query: Optional[Annotated[str, Field(strict=True, max_length=2000)]] = None
    method: Optional[StrictStr] = Field(default='hybrid', description="Retrieval strategy: \"keyword\" (lexical), \"vector\" (embedding similarity) or \"hybrid\" (default, both).")
    page: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=1, description="Filter-only page number; query search supports page 1 only")
    top_k: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = Field(default=10, description="Maximum number of topics to return, 1 to 100 (default 10). On a query search the server also bounds the result by its rerank pool — 50 candidates by default — so asking for more than that returns what the pool held. On a filter-only request (tags without a query) it is the page size instead, and `page` walks the rest.")
    score_threshold: Optional[Union[StrictFloat, StrictInt]] = None
    include: Optional[List[StrictStr]] = Field(default=None, description="e.g. ['content']")
    boost_tag_ids: Optional[Annotated[List[Annotated[str, Field(min_length=1, strict=True, max_length=128)]], Field(max_length=100)]] = Field(default=None, description="Reweight, do not filter: topics carrying these tags are pushed up, and topics without them still come back. Use `filters.tag_ids` when the intent is to exclude everything else.")
    filters: Optional[SearchFilters] = Field(default=None, description="Optional filters narrowing what is searched.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["query", "method", "page", "top_k", "score_threshold", "include", "boost_tag_ids", "filters"]

    @field_validator('method')
    def method_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['keyword', 'vector', 'hybrid']):
            raise ValueError("must be one of enum values ('keyword', 'vector', 'hybrid')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of filters
        if self.filters:
            _dict['filters'] = self.filters.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if query (nullable) is None
        # and model_fields_set contains the field
        if self.query is None and "query" in self.model_fields_set:
            _dict['query'] = None

        # set to None if score_threshold (nullable) is None
        # and model_fields_set contains the field
        if self.score_threshold is None and "score_threshold" in self.model_fields_set:
            _dict['score_threshold'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "query": obj.get("query"),
            "method": obj.get("method") if obj.get("method") is not None else 'hybrid',
            "page": obj.get("page") if obj.get("page") is not None else 1,
            "top_k": obj.get("top_k") if obj.get("top_k") is not None else 10,
            "score_threshold": obj.get("score_threshold"),
            "include": obj.get("include"),
            "boost_tag_ids": obj.get("boost_tag_ids"),
            "filters": SearchFilters.from_dict(obj["filters"]) if obj.get("filters") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


