# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from everos_cloud.models.topic_list_item import TopicListItem
from typing import Optional, Set
from typing_extensions import Self

class TopicListData(BaseModel):
    """
    A document's topic tree, DFS-ordered (flat list; build the tree from `parent_id`).  The list INCLUDES the synthetic document-root item (`type=root`), so ``len(topics) == document.topic_count + 1`` — the document's ``topic_count`` counts real topics only. Two consumer recipes:  * **Full tree** — root at the item whose ``parent_id`` is null, link the rest by   ``parent_id``. Returned order is already DFS, so children keep document order. * **Real topics only** (to match ``topic_count``) — drop the ``type=root`` item AND   null out the ``parent_id`` of its direct children, otherwise those now point at an id   that is no longer in the set.  Robust root test for either recipe: ``parent_id is null OR parent_id not in the returned ids`` — that also survives an orphan row left behind by a partial cascade delete.  ``include=content`` hydrates every item's body, which can grow the response by orders of magnitude. Ask for it to render a whole document, not to draw the tree.
    """ # noqa: E501
    topics: Optional[List[TopicListItem]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["topics"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TopicListData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in topics (list)
        _items = []
        if self.topics:
            for _item_topics in self.topics:
                if _item_topics:
                    _items.append(_item_topics.to_dict())
            _dict['topics'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TopicListData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "topics": [TopicListItem.from_dict(_item) for _item in obj["topics"]] if obj.get("topics") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


