# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class TopicTagWriteData(BaseModel):
    """
    TopicTagWriteData
    """ # noqa: E501
    topic_id: StrictStr = Field(description="The topic whose tag snapshot was written.")
    requested: Annotated[int, Field(strict=True, ge=0)] = Field(description="Stable-distinct request id count; not vocabulary-validity count")
    tag_ids: Annotated[List[Annotated[str, Field(min_length=1, strict=True, max_length=128)]], Field(max_length=50)] = Field(description="Complete materialized topic tag snapshot after the accepted write")
    version: Annotated[int, Field(strict=True, ge=0)] = Field(description="Current topic tag version")
    truncated: StrictBool = Field(description="Whether distinct input exceeded the store limit")
    limit: StrictInt = Field(description="Materialized topic tag limit")
    dropped_count: Annotated[int, Field(strict=True, ge=0)] = Field(description="Distinct requested ids omitted by stable truncation")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["topic_id", "requested", "tag_ids", "version", "truncated", "limit", "dropped_count"]

    @field_validator('limit')
    def limit_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set([50]):
            raise ValueError("must be one of enum values (50)")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TopicTagWriteData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TopicTagWriteData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "topic_id": obj.get("topic_id"),
            "requested": obj.get("requested"),
            "tag_ids": obj.get("tag_ids"),
            "version": obj.get("version"),
            "truncated": obj.get("truncated"),
            "limit": obj.get("limit"),
            "dropped_count": obj.get("dropped_count")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


