# coding: utf-8

"""
    EverOS Cloud Memory API

    Official Python client for the EverOS Cloud Memory API. Add, search, retrieve, and manage long-term memory for your AI applications over a typed interface (pydantic v2, with full type hints). Install and usage guides: https://github.com/EverMind-AI/everos-cloud-sdk-python

    The version of the OpenAPI document: 2.0.0
    Contact: service@evermind.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from everos_cloud_sdk.models.filter_node import FilterNode
from typing import Optional, Set
from typing_extensions import Self

class SearchInput(BaseModel):
    """
    SearchInput
    """ # noqa: E501
    app_id: Optional[StrictStr] = 'default'
    project_id: Optional[StrictStr] = 'default'
    user_id: Optional[StrictStr] = None
    agent_id: Optional[StrictStr] = None
    query: Annotated[str, Field(min_length=1, strict=True)]
    method: Optional[StrictStr] = 'hybrid'
    top_k: Optional[StrictInt] = -1
    radius: Optional[Union[Annotated[float, Field(le=1.0, strict=True, ge=0.0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = None
    min_score: Optional[Union[Annotated[float, Field(le=1.0, strict=True, ge=0.0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = None
    include_profile: Optional[StrictBool] = False
    enable_llm_rerank: Optional[StrictBool] = False
    filters: Optional[FilterNode] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["app_id", "project_id", "user_id", "agent_id", "query", "method", "top_k", "radius", "min_score", "include_profile", "enable_llm_rerank", "filters"]

    @field_validator('method')
    def method_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['keyword', 'vector', 'hybrid', 'agentic']):
            raise ValueError("must be one of enum values ('keyword', 'vector', 'hybrid', 'agentic')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of filters
        if self.filters:
            _dict['filters'] = self.filters.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if user_id (nullable) is None
        # and model_fields_set contains the field
        if self.user_id is None and "user_id" in self.model_fields_set:
            _dict['user_id'] = None

        # set to None if agent_id (nullable) is None
        # and model_fields_set contains the field
        if self.agent_id is None and "agent_id" in self.model_fields_set:
            _dict['agent_id'] = None

        # set to None if radius (nullable) is None
        # and model_fields_set contains the field
        if self.radius is None and "radius" in self.model_fields_set:
            _dict['radius'] = None

        # set to None if min_score (nullable) is None
        # and model_fields_set contains the field
        if self.min_score is None and "min_score" in self.model_fields_set:
            _dict['min_score'] = None

        # set to None if filters (nullable) is None
        # and model_fields_set contains the field
        if self.filters is None and "filters" in self.model_fields_set:
            _dict['filters'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "app_id": obj.get("app_id") if obj.get("app_id") is not None else 'default',
            "project_id": obj.get("project_id") if obj.get("project_id") is not None else 'default',
            "user_id": obj.get("user_id"),
            "agent_id": obj.get("agent_id"),
            "query": obj.get("query"),
            "method": obj.get("method") if obj.get("method") is not None else 'hybrid',
            "top_k": obj.get("top_k") if obj.get("top_k") is not None else -1,
            "radius": obj.get("radius"),
            "min_score": obj.get("min_score"),
            "include_profile": obj.get("include_profile") if obj.get("include_profile") is not None else False,
            "enable_llm_rerank": obj.get("enable_llm_rerank") if obj.get("enable_llm_rerank") is not None else False,
            "filters": FilterNode.from_dict(obj["filters"]) if obj.get("filters") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


