# coding: utf-8

"""
    EverOS Cloud Memory API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from everos_cloud_sdk.models.search_agent_case_item import SearchAgentCaseItem
from everos_cloud_sdk.models.search_agent_skill_item import SearchAgentSkillItem
from everos_cloud_sdk.models.search_episode_item import SearchEpisodeItem
from everos_cloud_sdk.models.search_profile_item import SearchProfileItem
from everos_cloud_sdk.models.unprocessed_message_dto import UnprocessedMessageDTO
from typing import Optional, Set
from typing_extensions import Self

class SearchData(BaseModel):
    """
    SearchData
    """ # noqa: E501
    episodes: Optional[List[SearchEpisodeItem]] = None
    profiles: Optional[List[SearchProfileItem]] = None
    agent_cases: Optional[List[SearchAgentCaseItem]] = None
    agent_skills: Optional[List[SearchAgentSkillItem]] = None
    unprocessed_messages: Optional[List[UnprocessedMessageDTO]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["episodes", "profiles", "agent_cases", "agent_skills", "unprocessed_messages"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in episodes (list)
        _items = []
        if self.episodes:
            for _item_episodes in self.episodes:
                if _item_episodes:
                    _items.append(_item_episodes.to_dict())
            _dict['episodes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in profiles (list)
        _items = []
        if self.profiles:
            for _item_profiles in self.profiles:
                if _item_profiles:
                    _items.append(_item_profiles.to_dict())
            _dict['profiles'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in agent_cases (list)
        _items = []
        if self.agent_cases:
            for _item_agent_cases in self.agent_cases:
                if _item_agent_cases:
                    _items.append(_item_agent_cases.to_dict())
            _dict['agent_cases'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in agent_skills (list)
        _items = []
        if self.agent_skills:
            for _item_agent_skills in self.agent_skills:
                if _item_agent_skills:
                    _items.append(_item_agent_skills.to_dict())
            _dict['agent_skills'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in unprocessed_messages (list)
        _items = []
        if self.unprocessed_messages:
            for _item_unprocessed_messages in self.unprocessed_messages:
                if _item_unprocessed_messages:
                    _items.append(_item_unprocessed_messages.to_dict())
            _dict['unprocessed_messages'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "episodes": [SearchEpisodeItem.from_dict(_item) for _item in obj["episodes"]] if obj.get("episodes") is not None else None,
            "profiles": [SearchProfileItem.from_dict(_item) for _item in obj["profiles"]] if obj.get("profiles") is not None else None,
            "agent_cases": [SearchAgentCaseItem.from_dict(_item) for _item in obj["agent_cases"]] if obj.get("agent_cases") is not None else None,
            "agent_skills": [SearchAgentSkillItem.from_dict(_item) for _item in obj["agent_skills"]] if obj.get("agent_skills") is not None else None,
            "unprocessed_messages": [UnprocessedMessageDTO.from_dict(_item) for _item in obj["unprocessed_messages"]] if obj.get("unprocessed_messages") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


